version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql-$ENVIRONMENT
    restart: always
    env_file: ./.env
    environment:
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_TCP_PORT: 3306
    ports:
      - $DB_PORT:3306
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  backend:
    build:
      context: .
    container_name: backend-$ENVIRONMENT
    restart: always
    env_file: ./.env
    ports:
      - $PORT:$PORT
    depends_on:
      - mysql
    volumes:
      - uploads-data:/app/uploads  
  frontend:
    build:
      context: ../front/
    container_name: frontend-$ENVIRONMENT
    restart: always
    env_file: ./.env
    ports:
      - $FRONTEND_PORT:80
volumes: 
  db-config:
  db-data:
  uploads-data: